# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lease_credits_api import LeaseCreditsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLeaseCreditsApi(unittest.TestCase):
    """LeaseCreditsApi unit test stubs"""

    def setUp(self):
        self.api = LeaseCreditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_lease_credits_lease_credit_id(self):
        """Test case for delete_lease_credits_lease_credit_id

        Delete a Lease Credit  # noqa: E501
        """
        pass

    def test_get_lease_credit(self):
        """Test case for get_lease_credit

        Retrieve a Lease Credit  # noqa: E501
        """
        pass

    def test_get_lease_credits(self):
        """Test case for get_lease_credits

        List all Lease Credits  # noqa: E501
        """
        pass

    def test_post_lease_credit(self):
        """Test case for post_lease_credit

        Create a Lease Credit  # noqa: E501
        """
        pass

    def test_put_lease_credit(self):
        """Test case for put_lease_credit

        Update a Lease Credit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
