# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reports_api import ReportsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reports_balance_sheet(self):
        """Test case for get_reports_balance_sheet

        Balance Sheet  # noqa: E501
        """
        pass

    def test_get_reports_cash_flow_statement(self):
        """Test case for get_reports_cash_flow_statement

        Cash Flow Statement  # noqa: E501
        """
        pass

    def test_get_reports_profit_and_loss(self):
        """Test case for get_reports_profit_and_loss

        Profit & Loss  # noqa: E501
        """
        pass

    def test_get_reports_rent_roll(self):
        """Test case for get_reports_rent_roll

        Rent Roll  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
