# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.communications_api import CommunicationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommunicationsApi(unittest.TestCase):
    """CommunicationsApi unit test stubs"""

    def setUp(self):
        self.api = CommunicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_communication(self):
        """Test case for delete_communication

        Delete a Communication  # noqa: E501
        """
        pass

    def test_get_communication(self):
        """Test case for get_communication

        Retrieve a Communication  # noqa: E501
        """
        pass

    def test_get_communications(self):
        """Test case for get_communications

        List all Communication Logs  # noqa: E501
        """
        pass

    def test_post_communication(self):
        """Test case for post_communication

        Create a Communication Log  # noqa: E501
        """
        pass

    def test_put_communication(self):
        """Test case for put_communication

        Update a Communication  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
