# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.expenses_api import ExpensesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExpensesApi(unittest.TestCase):
    """ExpensesApi unit test stubs"""

    def setUp(self):
        self.api = ExpensesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_expense(self):
        """Test case for delete_expense

        Delete an Expense  # noqa: E501
        """
        pass

    def test_get_expense(self):
        """Test case for get_expense

        Retrieve an Expense  # noqa: E501
        """
        pass

    def test_get_expenses(self):
        """Test case for get_expenses

        List all Expenses  # noqa: E501
        """
        pass

    def test_post_expense(self):
        """Test case for post_expense

        Create an Expense  # noqa: E501
        """
        pass

    def test_put_expense(self):
        """Test case for put_expense

        Update an Expense  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
