# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tenants_api import TenantsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self):
        self.api = TenantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tenant(self):
        """Test case for delete_tenant

        Delete a Tenant  # noqa: E501
        """
        pass

    def test_get_tenant(self):
        """Test case for get_tenant

        Retrieve a Tenant  # noqa: E501
        """
        pass

    def test_get_tenants(self):
        """Test case for get_tenants

        Retrieve all Tenants  # noqa: E501
        """
        pass

    def test_post_tenant(self):
        """Test case for post_tenant

        Create a Prospect  # noqa: E501
        """
        pass

    def test_put_tenant(self):
        """Test case for put_tenant

        Update a Tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
