# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.files_api import FilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Delete a File  # noqa: E501
        """
        pass

    def test_download_file(self):
        """Test case for download_file

        Download a File  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Retrieve a File  # noqa: E501
        """
        pass

    def test_get_files(self):
        """Test case for get_files

        List all Files  # noqa: E501
        """
        pass

    def test_post_files(self):
        """Test case for post_files

        Upload a File  # noqa: E501
        """
        pass

    def test_put_file(self):
        """Test case for put_file

        Update a File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
