# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.portfolios_api import PortfoliosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPortfoliosApi(unittest.TestCase):
    """PortfoliosApi unit test stubs"""

    def setUp(self):
        self.api = PortfoliosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_property_group(self):
        """Test case for get_property_group

        Retrieve a Portfolio  # noqa: E501
        """
        pass

    def test_get_property_groups(self):
        """Test case for get_property_groups

        List all Portfolios  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
