# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vendors_api import VendorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVendorsApi(unittest.TestCase):
    """VendorsApi unit test stubs"""

    def setUp(self):
        self.api = VendorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_vendor(self):
        """Test case for delete_vendor

        Delete a Vendor  # noqa: E501
        """
        pass

    def test_get_vendor(self):
        """Test case for get_vendor

        Retrieve a Vendor  # noqa: E501
        """
        pass

    def test_get_vendors(self):
        """Test case for get_vendors

        List all Vendors  # noqa: E501
        """
        pass

    def test_post_vendor(self):
        """Test case for post_vendor

        Create a Vendor  # noqa: E501
        """
        pass

    def test_put_vendor(self):
        """Test case for put_vendor

        Update a Vendor  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
