# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lease_payments_api import LeasePaymentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLeasePaymentsApi(unittest.TestCase):
    """LeasePaymentsApi unit test stubs"""

    def setUp(self):
        self.api = LeasePaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_lease_payment(self):
        """Test case for delete_lease_payment

        Delete a Lease Payment  # noqa: E501
        """
        pass

    def test_get_lease_payment(self):
        """Test case for get_lease_payment

        Retrieve a Lease Payment  # noqa: E501
        """
        pass

    def test_get_lease_payments(self):
        """Test case for get_lease_payments

        List all Lease Payments  # noqa: E501
        """
        pass

    def test_post_lease_payment(self):
        """Test case for post_lease_payment

        Create a Lease Payment  # noqa: E501
        """
        pass

    def test_put_lease_payment(self):
        """Test case for put_lease_payment

        Update a Lease Payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
