# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.units_api import UnitsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUnitsApi(unittest.TestCase):
    """UnitsApi unit test stubs"""

    def setUp(self):
        self.api = UnitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_unit(self):
        """Test case for get_unit

        Retrieve a Unit  # noqa: E501
        """
        pass

    def test_get_units(self):
        """Test case for get_units

        List all Units  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
