# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_user(self):
        """Test case for get_current_user

        Get Current User  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Retrieve a User  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        List all Users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
