# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lease_charges_api import LeaseChargesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLeaseChargesApi(unittest.TestCase):
    """LeaseChargesApi unit test stubs"""

    def setUp(self):
        self.api = LeaseChargesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_lease_charge(self):
        """Test case for delete_lease_charge

        Delete a Lease Credit  # noqa: E501
        """
        pass

    def test_get_lease_charge(self):
        """Test case for get_lease_charge

        Retrieve a Lease Charge  # noqa: E501
        """
        pass

    def test_get_lease_charges(self):
        """Test case for get_lease_charges

        List all Lease Charges  # noqa: E501
        """
        pass

    def test_post_lease_charge(self):
        """Test case for post_lease_charge

        Create a Lease Charge  # noqa: E501
        """
        pass

    def test_put_lease_charge(self):
        """Test case for put_lease_charge

        Update a Lease Charge  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
