# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_account(self):
        """Test case for delete_account

        Delete an Account  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Retrieve an Account  # noqa: E501
        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        List all Accounts  # noqa: E501
        """
        pass

    def test_post_account(self):
        """Test case for post_account

        Create an Account  # noqa: E501
        """
        pass

    def test_put_account(self):
        """Test case for put_account

        Update an Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
