# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lease_returned_payments_api import LeaseReturnedPaymentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLeaseReturnedPaymentsApi(unittest.TestCase):
    """LeaseReturnedPaymentsApi unit test stubs"""

    def setUp(self):
        self.api = LeaseReturnedPaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_lease_reversed_payment(self):
        """Test case for delete_lease_reversed_payment

        Delete a Lease Returned Payment  # noqa: E501
        """
        pass

    def test_get_lease_reversed_payment(self):
        """Test case for get_lease_reversed_payment

        Retrieve a Lease Returned Payment  # noqa: E501
        """
        pass

    def test_get_lease_reversed_payments(self):
        """Test case for get_lease_reversed_payments

        List all Lease Returned Payments  # noqa: E501
        """
        pass

    def test_post_lease_reversed_payments(self):
        """Test case for post_lease_reversed_payments

        Create a Lease Returned Payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
