# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notes_api import NotesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotesApi(unittest.TestCase):
    """NotesApi unit test stubs"""

    def setUp(self):
        self.api = NotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_note(self):
        """Test case for delete_note

        Delete a Note  # noqa: E501
        """
        pass

    def test_get_note(self):
        """Test case for get_note

        Retrieve a Note  # noqa: E501
        """
        pass

    def test_get_notes(self):
        """Test case for get_notes

        List all Notes  # noqa: E501
        """
        pass

    def test_post_notes(self):
        """Test case for post_notes

        Create a Note  # noqa: E501
        """
        pass

    def test_put_note(self):
        """Test case for put_note

        Update a Note  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
