# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.properties_api import PropertiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPropertiesApi(unittest.TestCase):
    """PropertiesApi unit test stubs"""

    def setUp(self):
        self.api = PropertiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_properties(self):
        """Test case for get_properties

        List all Properties  # noqa: E501
        """
        pass

    def test_get_property(self):
        """Test case for get_property

        Retrieve a Property  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
