# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.property_class import PropertyClass  # noqa: E501
from swagger_client.rest import ApiException


class TestPropertyClass(unittest.TestCase):
    """PropertyClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertyClass(self):
        """Test PropertyClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.property_class.PropertyClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
