# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.leases_api import LeasesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLeasesApi(unittest.TestCase):
    """LeasesApi unit test stubs"""

    def setUp(self):
        self.api = LeasesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_lease(self):
        """Test case for get_lease

        Retrieve a Lease  # noqa: E501
        """
        pass

    def test_get_lease_tenants(self):
        """Test case for get_lease_tenants

        List all Lease Tenants  # noqa: E501
        """
        pass

    def test_get_leases(self):
        """Test case for get_leases

        List all Leases  # noqa: E501
        """
        pass

    def test_post_leases_move_in(self):
        """Test case for post_leases_move_in

        Move in Tenant  # noqa: E501
        """
        pass

    def test_post_leases_move_out(self):
        """Test case for post_leases_move_out

        Move out Tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
