# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vendor_bills_api import VendorBillsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVendorBillsApi(unittest.TestCase):
    """VendorBillsApi unit test stubs"""

    def setUp(self):
        self.api = VendorBillsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_vendor_bill(self):
        """Test case for delete_vendor_bill

        Delete a Vendor Bill  # noqa: E501
        """
        pass

    def test_get_vendor_bill(self):
        """Test case for get_vendor_bill

        Retrieve a Vendor Bill  # noqa: E501
        """
        pass

    def test_get_vendor_bills(self):
        """Test case for get_vendor_bills

        List all Vendor Bills  # noqa: E501
        """
        pass

    def test_post_vendor_bill(self):
        """Test case for post_vendor_bill

        Create a Vendor Bill  # noqa: E501
        """
        pass

    def test_put_vendor_bill(self):
        """Test case for put_vendor_bill

        Update a Vendor Bill  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
