# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tasks_api import TasksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_task(self):
        """Test case for delete_task

        Deletes a Task  # noqa: E501
        """
        pass

    def test_get_task(self):
        """Test case for get_task

        Retrieve a Task  # noqa: E501
        """
        pass

    def test_get_tasks(self):
        """Test case for get_tasks

        Retrieve all Tasks  # noqa: E501
        """
        pass

    def test_post_task(self):
        """Test case for post_task

        Create a Task  # noqa: E501
        """
        pass

    def test_post_task_update(self):
        """Test case for post_task_update

        Post an Update on a Task  # noqa: E501
        """
        pass

    def test_put_task(self):
        """Test case for put_task

        Update a Task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
