# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.owners_api import OwnersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOwnersApi(unittest.TestCase):
    """OwnersApi unit test stubs"""

    def setUp(self):
        self.api = OwnersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_owner(self):
        """Test case for delete_owner

        Delete an Owner  # noqa: E501
        """
        pass

    def test_get_owner(self):
        """Test case for get_owner

        Retrieve an Owner  # noqa: E501
        """
        pass

    def test_get_owners(self):
        """Test case for get_owners

        List all Owners  # noqa: E501
        """
        pass

    def test_post_owner(self):
        """Test case for post_owner

        Create an Owner  # noqa: E501
        """
        pass

    def test_put_owner(self):
        """Test case for put_owner

        Update an Owner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
