# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LeasesMoveinBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lease_id': 'MongoId',
        'move_in_at': 'object',
        'tenant_ids': 'object',
        'portal_enabled': 'object'
    }

    attribute_map = {
        'lease_id': 'leaseId',
        'move_in_at': 'moveInAt',
        'tenant_ids': 'tenantIds',
        'portal_enabled': 'portalEnabled'
    }

    def __init__(self, lease_id=None, move_in_at=None, tenant_ids=None, portal_enabled=None):  # noqa: E501
        """LeasesMoveinBody - a model defined in Swagger"""  # noqa: E501
        self._lease_id = None
        self._move_in_at = None
        self._tenant_ids = None
        self._portal_enabled = None
        self.discriminator = None
        self.lease_id = lease_id
        self.move_in_at = move_in_at
        self.tenant_ids = tenant_ids
        self.portal_enabled = portal_enabled

    @property
    def lease_id(self):
        """Gets the lease_id of this LeasesMoveinBody.  # noqa: E501


        :return: The lease_id of this LeasesMoveinBody.  # noqa: E501
        :rtype: MongoId
        """
        return self._lease_id

    @lease_id.setter
    def lease_id(self, lease_id):
        """Sets the lease_id of this LeasesMoveinBody.


        :param lease_id: The lease_id of this LeasesMoveinBody.  # noqa: E501
        :type: MongoId
        """
        if lease_id is None:
            raise ValueError("Invalid value for `lease_id`, must not be `None`")  # noqa: E501

        self._lease_id = lease_id

    @property
    def move_in_at(self):
        """Gets the move_in_at of this LeasesMoveinBody.  # noqa: E501

        Format: YYYY-MM-DD  # noqa: E501

        :return: The move_in_at of this LeasesMoveinBody.  # noqa: E501
        :rtype: object
        """
        return self._move_in_at

    @move_in_at.setter
    def move_in_at(self, move_in_at):
        """Sets the move_in_at of this LeasesMoveinBody.

        Format: YYYY-MM-DD  # noqa: E501

        :param move_in_at: The move_in_at of this LeasesMoveinBody.  # noqa: E501
        :type: object
        """
        if move_in_at is None:
            raise ValueError("Invalid value for `move_in_at`, must not be `None`")  # noqa: E501

        self._move_in_at = move_in_at

    @property
    def tenant_ids(self):
        """Gets the tenant_ids of this LeasesMoveinBody.  # noqa: E501

        An array of Tenant Ids to move in  # noqa: E501

        :return: The tenant_ids of this LeasesMoveinBody.  # noqa: E501
        :rtype: object
        """
        return self._tenant_ids

    @tenant_ids.setter
    def tenant_ids(self, tenant_ids):
        """Sets the tenant_ids of this LeasesMoveinBody.

        An array of Tenant Ids to move in  # noqa: E501

        :param tenant_ids: The tenant_ids of this LeasesMoveinBody.  # noqa: E501
        :type: object
        """
        if tenant_ids is None:
            raise ValueError("Invalid value for `tenant_ids`, must not be `None`")  # noqa: E501

        self._tenant_ids = tenant_ids

    @property
    def portal_enabled(self):
        """Gets the portal_enabled of this LeasesMoveinBody.  # noqa: E501


        :return: The portal_enabled of this LeasesMoveinBody.  # noqa: E501
        :rtype: object
        """
        return self._portal_enabled

    @portal_enabled.setter
    def portal_enabled(self, portal_enabled):
        """Sets the portal_enabled of this LeasesMoveinBody.


        :param portal_enabled: The portal_enabled of this LeasesMoveinBody.  # noqa: E501
        :type: object
        """
        if portal_enabled is None:
            raise ValueError("Invalid value for `portal_enabled`, must not be `None`")  # noqa: E501

        self._portal_enabled = portal_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LeasesMoveinBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LeasesMoveinBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
