# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Note(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'MongoId',
        'title': 'object',
        'body': 'object',
        'tags': 'object',
        'linked_resource': 'NoteLinkedResource',
        'created_at': 'object',
        'created_by': 'object'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'body': 'body',
        'tags': 'tags',
        'linked_resource': 'linkedResource',
        'created_at': 'createdAt',
        'created_by': 'createdBy'
    }

    def __init__(self, id=None, title=None, body=None, tags=None, linked_resource=None, created_at=None, created_by=None):  # noqa: E501
        """Note - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._title = None
        self._body = None
        self._tags = None
        self._linked_resource = None
        self._created_at = None
        self._created_by = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.title = title
        if body is not None:
            self.body = body
        if tags is not None:
            self.tags = tags
        self.linked_resource = linked_resource
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by

    @property
    def id(self):
        """Gets the id of this Note.  # noqa: E501


        :return: The id of this Note.  # noqa: E501
        :rtype: MongoId
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Note.


        :param id: The id of this Note.  # noqa: E501
        :type: MongoId
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this Note.  # noqa: E501


        :return: The title of this Note.  # noqa: E501
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Note.


        :param title: The title of this Note.  # noqa: E501
        :type: object
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def body(self):
        """Gets the body of this Note.  # noqa: E501


        :return: The body of this Note.  # noqa: E501
        :rtype: object
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this Note.


        :param body: The body of this Note.  # noqa: E501
        :type: object
        """

        self._body = body

    @property
    def tags(self):
        """Gets the tags of this Note.  # noqa: E501


        :return: The tags of this Note.  # noqa: E501
        :rtype: object
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Note.


        :param tags: The tags of this Note.  # noqa: E501
        :type: object
        """

        self._tags = tags

    @property
    def linked_resource(self):
        """Gets the linked_resource of this Note.  # noqa: E501


        :return: The linked_resource of this Note.  # noqa: E501
        :rtype: NoteLinkedResource
        """
        return self._linked_resource

    @linked_resource.setter
    def linked_resource(self, linked_resource):
        """Sets the linked_resource of this Note.


        :param linked_resource: The linked_resource of this Note.  # noqa: E501
        :type: NoteLinkedResource
        """
        if linked_resource is None:
            raise ValueError("Invalid value for `linked_resource`, must not be `None`")  # noqa: E501

        self._linked_resource = linked_resource

    @property
    def created_at(self):
        """Gets the created_at of this Note.  # noqa: E501

        Read Only  # noqa: E501

        :return: The created_at of this Note.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Note.

        Read Only  # noqa: E501

        :param created_at: The created_at of this Note.  # noqa: E501
        :type: object
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this Note.  # noqa: E501

        Read Only  # noqa: E501

        :return: The created_by of this Note.  # noqa: E501
        :rtype: object
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Note.

        Read Only  # noqa: E501

        :param created_by: The created_by of this Note.  # noqa: E501
        :type: object
        """

        self._created_by = created_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Note, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Note):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
