# coding: utf-8

"""
    DoorLoop API Reference

    It does some pretty cool stuff and gives you complete access to DoorLoop's data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@doorloop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PropertyType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    RESIDENTIAL_SINGLE_FAMILY = "RESIDENTIAL_SINGLE_FAMILY"
    RESIDENTIAL_MULTI_FAMILY = "RESIDENTIAL_MULTI_FAMILY"
    RESIDENTIAL_CONDO = "RESIDENTIAL_CONDO"
    RESIDENTIAL_TOWNHOME = "RESIDENTIAL_TOWNHOME"
    RESIDENTIAL_OTHER = "RESIDENTIAL_OTHER"
    COMMERCIAL_OTHER = "COMMERCIAL_OTHER"
    COMMERCIAL_INDUSTRIAL = "COMMERCIAL_INDUSTRIAL"
    COMMERCIAL_OFFICE = "COMMERCIAL_OFFICE"
    COMMERCIAL_RETAIL = "COMMERCIAL_RETAIL"
    COMMERCIAL_SHOPPING_CENTER = "COMMERCIAL_SHOPPING_CENTER"
    COMMERCIAL_STORAGE = "COMMERCIAL_STORAGE"
    COMMERCIAL_PARKING = "COMMERCIAL_PARKING"
    COMMERCIAL_CO_WORKING = "COMMERCIAL_CO_WORKING"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """PropertyType - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PropertyType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PropertyType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
